export enum EntitiesTypes {
  FETCH_COMPANY_PROFILE = "@entities/FETCH_COMPANY_PROFILE_REQ",
  FETCH_COMPANY_PROFILE_FAIL = "@entities/FETCH_COMPANY_PROFILE_FAIL_REQ",
  FETCH_COMPANY_PROFILE_SUCCESS = "@entities/FETCH_COMPANY_PROFILE_SUCCESS_REQ",
}